_wandb:
    value:
        cli_version: 0.24.0
        e:
            las7u2wggeum8ots88onfpcdn1k4ob94:
                args:
                    - --epochs
                    - "5"
                    - --batch_size
                    - "16"
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 16
                cpu_count_logical: 24
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "982820896768"
                        used: "926017540096"
                email: baonhipct@gmail.com
                executable: /home/ml4u/miniconda3/envs/object-removal/bin/python
                gpu: NVIDIA GeForce RTX 4090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-f7dc9cb9-69f7-a186-aff5-25b51c74de48
                host: ml4u
                memory:
                    total: "67152138240"
                os: Linux-6.8.0-90-generic-x86_64-with-glibc2.35
                program: /home/ml4u/BKTeam/source/BaoNhi/Object-Removal/src/refinement/train.py
                python: CPython 3.9.25
                root: /home/ml4u/BKTeam/source/BaoNhi/Object-Removal/src/refinement
                startedAt: "2026-02-04T05:35:25.568975Z"
                writerId: las7u2wggeum8ots88onfpcdn1k4ob94
        m: []
        python_version: 3.9.25
        t:
            "1":
                - 1
                - 41
                - 105
            "2":
                - 1
                - 41
                - 105
            "3":
                - 13
                - 16
            "4": 3.9.25
            "5": 0.24.0
            "12": 0.24.0
            "13": linux-x86_64
batch_size:
    value: 16
epochs:
    value: 5
lr:
    value: 0.0002
model:
    value: UNet
