_wandb:
    value:
        cli_version: 0.24.0
        e:
            2yj3hvc0e6lat4sbn5ff06nz69g7sfdd:
                email: baonhipct@gmail.com
                executable: /home/ml4u/miniconda3/envs/object-removal/bin/python
                host: ml4u
                os: Linux-6.8.0-90-generic-x86_64-with-glibc2.35
                program: <stdin>
                python: CPython 3.9.25
                root: /home/ml4u/BKTeam/source/BaoNhi/Object-Removal
                startedAt: "2026-01-25T17:13:03.507365Z"
                writerId: 2yj3hvc0e6lat4sbn5ff06nz69g7sfdd
        m: []
        python_version: 3.9.25
        t:
            "3":
                - 2
            "4": 3.9.25
            "5": 0.24.0
            "12": 0.24.0
            "13": linux-x86_64
